const app = require('express')();

// list of 10 books generated by github copilot
const books = [
    { title: 'The Alchemist', author: 'Paulo Coelho' },
    { title: 'The God of Small Things', author: 'Arundhati Roy' },
    { title: 'The White Tiger', author: 'Aravind Adiga' },
    { title: 'The Kite Runner', author: 'Khaled Hosseini' },
    { title: 'The Catcher in the Rye', author: 'J.D. Salinger' },
    { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
    { title: 'The Da Vinci Code', author: 'Dan Brown' },
    { title: 'The Hobbit', author: 'J.R.R. Tolkien' },
    { title: 'The Lord of the Rings', author: 'J.R.R. Tolkien' },
    { title: 'The Hunger Games', author: 'Suzanne Collins' },
    { title: 'Angels and Demons', author: 'Dan Brown' },
    { title: 'The Lost Symbol', author: 'Dan Brown' },
    { title: 'Inferno', author: 'Dan Brown' },
    { title: 'Origin', author: 'Dan Brown' },
    { title: 'Digital Fortress', author: 'Dan Brown' }
]

app.get('/', (req, res) => {
    res.send(books);
});

app.get('/books/:book', (req, res) => {
    const book = books.find(book => book.title === req.params.book);
    if (!book) {
        return res.send(404, 'Book not found');
    }
    res.send(book);
});

app.get('/authors/:author', (req, res) => {
    const author = books.filter(book => book.author === req.params.author);
    if (author.length === 0) {
        return res.send(404, 'Author not found');
    }
    res.send(author);
});

app.listen(3000, () => {
    console.log('Server is running on port 3000');
});